ALTER TABLE users
    ALTER COLUMN phone_number DROP NOT NULL;

ALTER TABLE sellers
    ALTER COLUMN garage_name DROP NOT NULL,
    ALTER COLUMN city DROP NOT NULL,
    ALTER COLUMN region DROP NOT NULL,
    ALTER COLUMN address DROP NOT NULL;

ALTER TABLE researchers
    ALTER COLUMN city DROP NOT NULL,
    ALTER COLUMN region DROP NOT NULL,
    ALTER COLUMN address DROP NOT NULL;