CREATE TYPE user_type AS ENUM ('RESEARCHER', 'SELLER', 'MANAGER');

CREATE TYPE user_status AS ENUM ('ENABLED', 'DISABLED', 'SUSPENDED');

CREATE TYPE city AS ENUM ('ANTANANARIVO');

CREATE TYPE region AS ENUM ('ANALAMANGA');

CREATE TYPE manager_role AS ENUM ('ADMIN', 'MANAGER');